name: MyLogicApp-Build

on:
  push:
    branches:
      - main
      - 'features/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim
    
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite:3.34.0
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Azure Functions Core Tools via apt
      - name: Install Azure Functions Core Tools
        run: |
          apt update && \
          apt install -y gpg wget && \
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-prod.gpg && \
          wget -q https://packages.microsoft.com/config/debian/12/prod.list && \
          mv prod.list /etc/apt/sources.list.d/microsoft-prod.list && \
          chown root:root /usr/share/keyrings/microsoft-prod.gpg && \
          chown root:root /etc/apt/sources.list.d/microsoft-prod.list && \
          apt update && \
          apt install -y azure-functions-core-tools-4 libicu-dev && \
          chmod +x /usr/lib/azure-functions-core-tools-4/in-proc6/func && \
          chmod +x /usr/lib/azure-functions-core-tools-4/in-proc8/func && \
          rm -rf /var/lib/apt/lists/*

      # Build .NET solution
      - name: Restore dependencies
        run: dotnet restore tests/MyLogicAppTests/MyLogicAppTests.csproj

      - name: Build
        run: dotnet build tests/MyLogicAppTests/MyLogicAppTests.csproj --no-restore

      # Check software versions
      - name: Check dotnet SDK installation
        run: 'dotnet --info'

      - name: Check Functions Core tools installation
        run: 'func --version'

      - name: Check PATH
        run: "echo $PATH | tr ':' '\n'"

      # Run tests
      - name: Run tests
        run: dotnet test tests/MyLogicAppTests/MyLogicAppTests.csproj --no-restore --verbosity normal -- --report-trx --report-trx-filename TestResults.trx

      # Publish artefacts and test results
      - name: Publish test log
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: tests/MyLogicAppTests/**/TestResults.trx
