name: MyLogicApp-Build

on:
  push:
    branches:
      - main
      - 'features/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js (required for Azure Functions Core Tools and Azurite)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Build .NET solution
      - name: Restore dependencies
        run: dotnet restore tests/MyLogicAppTests/MyLogicAppTests.csproj

      - name: Build
        run: dotnet build tests/MyLogicAppTests/MyLogicAppTests.csproj --no-restore

      - name: Install Functions Core tools
        run: 'npm install -g azure-functions-core-tools@4 --unsafe-perm true'

      - name: Install Azurite
        run: 'npm install -g azurite@3.34.0'

      - name: Start Azurite services
        run: 'azurite --silent --location azurite-data --debug azurite-debug.log &'
        shell: bash

      # Check software versions
      - name: Check dotnet SDK installation
        run: 'dotnet --info'

      - name: Check node installation
        run: 'node --version'

      - name: Check Functions Core tools installation
        run: 'func --version'

      # Run tests
      - name: Run tests
        run: dotnet test tests/MyLogicAppTests/MyLogicAppTests.csproj --no-restore --verbosity normal -- --report-trx --report-trx-filename TestResults.trx

      # Publish artefacts and test results
      - name: Publish test log
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: tests/MyLogicAppTests/TestResults/*.trx
